#include "RecentBooksActivity.h"

#include <Bitmap.h>
#include <Epub.h>
#include <FontCacheManager.h>
#include <FsHelpers.h>
#include <GfxRenderer.h>
#include <HalStorage.h>
#include <I18n.h>
#include <JpegToBmpConverter.h>
#include <MangaPanel.h>
#include <Memory.h>
#include <PngToBmpConverter.h>
#include <Xtc.h>

#include <algorithm>
#include <cstdio>
#include <memory>

#include "BookStatsActivity.h"
#include "EpubProgressUtil.h"
#include "MappedInputManager.h"
#include "RecentBooksStore.h"
#include "XtcProgressUtil.h"
#include "components/UITheme.h"
#include "components/icons/cover.h"
#include "fontIds.h"

namespace {
constexpr unsigned long LONG_PRESS_MS = 1000;
constexpr int COVER_ASPECT_NUM = 2;
constexpr int COVER_ASPECT_DEN = 3;
constexpr int SHELF_THUMB_WIDTH = 36;
constexpr int SHELF_THUMB_HEIGHT = 54;
constexpr uint32_t THUMB_IDLE_MS = 2000;
constexpr size_t INDEX_IO_CHUNK_SIZE = 4096;
constexpr uint32_t COVER_WORKER_STACK = 8192;

namespace fui = freeink::ui;

bool readExactChunked(HalFile& file, void* output, const size_t length) {
  auto* bytes = static_cast<uint8_t*>(output);
  size_t offset = 0;
  while (offset < length) {
    const size_t count = std::min(INDEX_IO_CHUNK_SIZE, length - offset);
    if (file.read(bytes + offset, count) != static_cast<int>(count)) return false;
    offset += count;
  }
  return true;
}

bool writeExactChunked(HalFile& file, const void* input, const size_t length) {
  const auto* bytes = static_cast<const uint8_t*>(input);
  size_t offset = 0;
  while (offset < length) {
    const size_t count = std::min(INDEX_IO_CHUNK_SIZE, length - offset);
    if (file.write(bytes + offset, count) != count) return false;
    offset += count;
  }
  return true;
}

// Diagnostic artifact written by HalSystem::checkPanic() to the SD root -- a .txt file the
// library walk would otherwise list as a book.
bool isCrashReportFile(const char* name) { return strcmp(name, "crash_report.txt") == 0; }

// A cached cover thumb is only usable when it is exactly the requested height -- earlier builds
// generated aspect-fill thumbs that could come out TALLER than requested (e.g. 232px for a 226px
// request), which the home screen letterboxes into a white right stripe inside the cover frame.
bool thumbHeightValid(const std::string& thumbPath, const int h) {
  // Width must match the cover box too, not just the height: thumbs generated by an earlier
  // build are exactly `h` tall but narrower, which still needs a crop at draw time -- the slow
  // per-pixel path (~250ms per cover, and clicks are dropped during such a render). Checking
  // only the height let those survive forever.
  const int expectedW = (h * COVER_ASPECT_NUM) / COVER_ASPECT_DEN;
  HalFile f;
  if (!Storage.openFileForRead("LIB", thumbPath, f)) return false;
  Bitmap bmp(f);
  bool ok = bmp.parseHeaders() == BmpReaderError::Ok && bmp.getHeight() == h && bmp.getWidth() == expectedW;
  if (ok) {
    // The header alone does not prove the pixels are there: a generation that ran out of
    // memory (reported from an X3, whose larger viewport leaves less headroom) leaves a
    // truncated file whose header still reads correctly, and it then survives forever because
    // the height matches. Require the full pixel payload -- rows are 4-byte aligned.
    const uint32_t needed = static_cast<uint32_t>(bmp.getRowBytes()) * static_cast<uint32_t>(bmp.getHeight());
    // Compare against the pixel payload only; any sane header size is on top of it.
    if (static_cast<uint32_t>(f.size()) < needed) {
      LOG_DBG("LIB", "Discarding truncated thumb %s (%u < %u bytes)", thumbPath.c_str(), (unsigned)f.size(),
              (unsigned)needed);
      ok = false;
    }
  }
  f.close();
  return ok;
}

}  // namespace

void RecentBooksActivity::coverWorkerTrampoline(void* ctx) {
  static_cast<RecentBooksActivity*>(ctx)->coverWorkerLoop();
}

bool RecentBooksActivity::coverWorkerShouldCancel(void* ctx) {
  auto* self = static_cast<RecentBooksActivity*>(ctx);
  if (!self) return true;
  // NOT RenderLock::peek(). A redraw is not a reason to abandon a conversion: the worker is its
  // own FreeRTOS task, SD access is already serialised by HalStorage's mutex, and the Library's
  // own scan slices redraw often enough that any conversion longer than the gap between them was
  // cancelled and restarted from zero forever (device log: a 43KB BMP cover reached ~8s, was
  // cancelled, and began again -- it could never finish). Real user input still cancels
  // immediately: loop() sets coverWorkerCancelRequested_ on anyButtonDownRaw().
  const bool cancel = self->coverWorkerExitRequested_ || self->coverWorkerCancelRequested_;
  if (cancel) self->coverWorkerCancelSeen_ = true;
  return cancel;
}

void RecentBooksActivity::coverWorkerLoop() {
  while (true) {
    ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    if (coverWorkerExitRequested_) break;
    if (!coverWorkerBusy_.load(std::memory_order_acquire)) continue;
    runCoverJob();
    // Publishes coverResult_ to the loop task.
    coverWorkerBusy_.store(false, std::memory_order_release);
  }
  coverWorkerExited_ = true;
  vTaskDelete(nullptr);
}

void RecentBooksActivity::runCoverJob() {
  CoverResult result;
  result.book = coverJob_.book;
  result.fileSize = coverJob_.fileSize;
  result.modifiedStamp = coverJob_.modifiedStamp;

  const bool isEpub = FsHelpers::hasEpubExtension(result.book.path);
  const bool isXtc = FsHelpers::hasXtcExtension(result.book.path);
  if (!isEpub && !isXtc) {
    const manga::MangaBook mangaBook(result.book.path);
    const int targetHeight = coverJob_.targetHeight > 0 ? coverJob_.targetHeight : coverJob_.gridHeight;
    if (targetHeight > 0 && !thumbHeightValid(mangaBook.getThumbBmpPath(targetHeight), targetHeight)) {
      Storage.remove(mangaBook.getThumbBmpPath(targetHeight).c_str());
      mangaBook.generateThumbBmp(targetHeight, &coverWorkerShouldCancel, this);
    }
    result.hasGridThumb = thumbHeightValid(mangaBook.getThumbBmpPath(coverJob_.gridHeight), coverJob_.gridHeight);
    if (result.hasGridThumb) result.book.coverBmpPath = mangaBook.getThumbBmpPath();
  } else if (isEpub) {
    Epub epub(result.book.path, "/.crosspoint");
    const bool loaded = epub.load(true, true, &coverWorkerShouldCancel, this);
    const int targetHeight = coverJob_.targetHeight > 0 ? coverJob_.targetHeight : coverJob_.gridHeight;
    if (loaded && !coverWorkerShouldCancel(this) && targetHeight > 0 &&
        !thumbHeightValid(epub.getThumbBmpPath(targetHeight), targetHeight)) {
      epub.generateThumbBmp(targetHeight, &coverWorkerShouldCancel, this);
    }
    result.hasGridThumb = loaded && thumbHeightValid(epub.getThumbBmpPath(coverJob_.gridHeight), coverJob_.gridHeight);
    if (result.hasGridThumb) result.book.coverBmpPath = epub.getThumbBmpPath();
    if (loaded && !epub.getTitle().empty()) result.book.title = epub.getTitle();
    // Separate "there is nothing to render" from "it did not fit right now", the same split
    // HomeActivity::loadRecentCovers makes. Only a book that loaded and declares no cover is a
    // permanent fact worth recording; a failure with a cover present must stay retryable, or one
    // low-heap moment costs the cover forever. Requires !cancelled: a cancelled load leaves the
    // metadata cache unpopulated, which hasCoverImage() cannot distinguish from a coverless book.
    result.coverKnownAbsent = loaded && !result.hasGridThumb && !coverWorkerShouldCancel(this) && !epub.hasCoverImage();
    if (loaded && !result.hasGridThumb && !result.coverKnownAbsent) {
      LOG_ERR("RBA", "Cover thumb failed for %s; will retry", result.book.path.c_str());
    }
  } else {
    Xtc xtc(result.book.path, "/.crosspoint");
    const bool loaded = xtc.load();
    const int targetHeight = coverJob_.targetHeight > 0 ? coverJob_.targetHeight : coverJob_.gridHeight;
    if (loaded && !coverWorkerShouldCancel(this) && targetHeight > 0 &&
        !thumbHeightValid(xtc.getThumbBmpPath(targetHeight), targetHeight)) {
      xtc.generateThumbBmp(targetHeight, &coverWorkerShouldCancel, this);
    }
    result.hasGridThumb = loaded && thumbHeightValid(xtc.getThumbBmpPath(coverJob_.gridHeight), coverJob_.gridHeight);
    if (result.hasGridThumb) result.book.coverBmpPath = xtc.getThumbBmpPath();
    if (loaded && !xtc.getTitle().empty()) result.book.title = xtc.getTitle();
  }

  result.completed = !coverWorkerCancelSeen_ && !coverWorkerExitRequested_ && !coverWorkerCancelRequested_;
  result.pending = true;
  coverResult_ = std::move(result);
}

bool RecentBooksActivity::postCoverJob(CoverJob&& job) {
  if (!coverWorkerTask_ || coverWorkerBusy_.load(std::memory_order_acquire) || coverResult_.pending) return false;
  coverJob_ = std::move(job);
  coverResult_ = CoverResult{};
  coverWorkerCancelRequested_ = false;
  coverWorkerCancelSeen_ = false;
  // Publishes coverJob_ to the worker task.
  coverWorkerBusy_.store(true, std::memory_order_release);
  xTaskNotifyGive(coverWorkerTask_);
  return true;
}

void RecentBooksActivity::startCoverWorker() {
  coverWorkerExitRequested_ = false;
  coverWorkerExited_ = false;
  coverWorkerBusy_.store(false, std::memory_order_relaxed);
  coverWorkerCancelRequested_ = false;
  coverWorkerCancelSeen_ = false;
  coverResult_ = CoverResult{};
  if (xTaskCreate(&coverWorkerTrampoline, "LibraryCover", COVER_WORKER_STACK, this, 1, &coverWorkerTask_) != pdPASS) {
    coverWorkerTask_ = nullptr;
    LOG_ERR("RBA", "Failed to create cover worker; missing covers will wait for the next visit");
  }
}

void RecentBooksActivity::stopCoverWorker() {
  if (!coverWorkerTask_) return;
  coverWorkerExitRequested_ = true;
  coverWorkerCancelRequested_ = true;
  xTaskNotifyGive(coverWorkerTask_);
  while (!coverWorkerExited_) vTaskDelay(1);
  coverWorkerTask_ = nullptr;
}

int RecentBooksActivity::getCellHeight(int cellWidth) const {
  int coverWidth = cellWidth - 2 * COVER_PADDING;
  int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  int lineHeight = renderer.getLineHeight(SMALL_FONT_ID);
  return COVER_PADDING + coverHeight + CELL_TEXT_GAP + lineHeight + COVER_PADDING;
}

int RecentBooksActivity::getVisibleRows(int cellHeight, int contentHeight) const {
  if (cellHeight <= 0) return 1;
  // Rows are separated by GRID_ROW_GAP: N full rows need N*cellHeight + (N-1)*gap.
  return std::max(1, (contentHeight + GRID_ROW_GAP) / (cellHeight + GRID_ROW_GAP));
}

int RecentBooksActivity::getContentItemCount() const {
  if (selectedTab == 0) return static_cast<int>(recentBooks.size());
  return static_cast<int>(shelves.size());
}

namespace {
constexpr const char* LIBRARY_CACHE_JSON = "/.crosspoint/library_cache.json";
}  // namespace

void RecentBooksActivity::loadRecentBooks() {
  lastRendered.valid = false;  // content changing under the frame -> next render must be full
  // Recents first (most recently opened first), then the persisted result of the last card
  // scan -- instantly, without touching the card tree. A background re-scan (see
  // startLibraryScan) refreshes and re-persists the list afterwards.
  RecentBooksStore cache;
  if (cache.loadFromPath(LIBRARY_CACHE_JSON)) {
    recentBooks = cache.takeBooks();
    mergeRecentBooks(recentBooks, RECENT_BOOKS.getBooks());
  } else {
    recentBooks = RECENT_BOOKS.getBooks();
  }
}

namespace {
constexpr char LIBRARY_INDEX_PATH[] = "/.crosspoint/library.idx";
constexpr uint32_t LIBRARY_INDEX_MAGIC = 0x4C494258;  // "LIBX"
constexpr uint8_t LIBRARY_INDEX_VERSION = 3;
constexpr size_t LIBRARY_INDEX_MAX_ENTRIES = 2048;  // guards a corrupt count against the heap
}  // namespace

void RecentBooksActivity::loadLibraryIndex() {
  libraryIndex_.clear();
  libraryIndexDirty_ = false;

  HalFile f;
  if (!Storage.openFileForRead("LIB", LIBRARY_INDEX_PATH, f)) return;
  uint32_t magic = 0;
  uint8_t version = 0;
  uint32_t count = 0;
  if (f.read(&magic, sizeof(magic)) != sizeof(magic) || magic != LIBRARY_INDEX_MAGIC) return;
  if (f.read(&version, sizeof(version)) != sizeof(version) || version != LIBRARY_INDEX_VERSION) return;
  if (f.read(&count, sizeof(count)) != sizeof(count) || count > LIBRARY_INDEX_MAX_ENTRIES) return;

  libraryIndex_.resize(count);
  if (!readExactChunked(f, libraryIndex_.data(), libraryIndex_.size() * sizeof(LibraryIndexEntry))) {
    libraryIndex_.clear();  // truncated file: treat the whole index as absent
    return;
  }
  LOG_DBG("LIB", "Library index: %u entries", (unsigned)libraryIndex_.size());
}

void RecentBooksActivity::saveLibraryIndex() {
  if (!libraryIndexDirty_) return;
  HalFile f;
  if (!Storage.openFileForWrite("LIB", LIBRARY_INDEX_PATH, f)) return;
  const uint32_t magic = LIBRARY_INDEX_MAGIC;
  const uint8_t version = LIBRARY_INDEX_VERSION;
  const uint32_t count = static_cast<uint32_t>(libraryIndex_.size());
  const bool written = writeExactChunked(f, &magic, sizeof(magic)) && writeExactChunked(f, &version, sizeof(version)) &&
                       writeExactChunked(f, &count, sizeof(count)) &&
                       writeExactChunked(f, libraryIndex_.data(), libraryIndex_.size() * sizeof(LibraryIndexEntry));
  if (written) f.flush();
  f.close();
  if (written) libraryIndexDirty_ = false;
}

const RecentBooksActivity::LibraryIndexEntry* RecentBooksActivity::findIndexEntry(const uint32_t pathHash) const {
  const auto it = std::find_if(libraryIndex_.begin(), libraryIndex_.end(),
                               [pathHash](const LibraryIndexEntry& e) { return e.pathHash == pathHash; });
  return it != libraryIndex_.end() ? &*it : nullptr;
}

void RecentBooksActivity::recordIndexEntry(const std::string& path, const uint32_t fileSize,
                                           const uint32_t modifiedStamp, const int thumbHeight, const bool hasThumb,
                                           const bool coverKnownAbsent) {
  const uint32_t hash = static_cast<uint32_t>(std::hash<std::string>{}(path));
  LibraryIndexEntry entry;
  entry.pathHash = hash;
  entry.fileSize = fileSize;
  entry.modifiedStamp = modifiedStamp;
  entry.thumbHeight = static_cast<uint16_t>(thumbHeight);
  entry.flags = 0;
  if (hasThumb) entry.flags |= INDEX_FLAG_HAS_THUMB;
  // Only a caller that positively established the book has no cover sets this; every other
  // failure leaves the bit clear so the next visit tries again.
  if (coverKnownAbsent) entry.flags |= INDEX_FLAG_NO_COVER;

  for (auto& e : libraryIndex_) {
    if (e.pathHash != hash) continue;
    if (e.fileSize == entry.fileSize && e.modifiedStamp == entry.modifiedStamp && e.thumbHeight == entry.thumbHeight &&
        e.flags == entry.flags) {
      return;  // unchanged; no rewrite
    }
    e = entry;
    libraryIndexDirty_ = true;
    return;
  }
  if (libraryIndex_.size() >= LIBRARY_INDEX_MAX_ENTRIES) return;
  libraryIndex_.push_back(entry);
  libraryIndexDirty_ = true;
}

void RecentBooksActivity::startLibraryScan() {
  loadLibraryIndex();
  scan_ = LibraryScanState{};
  scan_.active = true;
  scan_.dirStack.reserve(16);
  scan_.results.reserve(recentBooks.size());
  scan_.dirStack.push_back("/");
}

bool RecentBooksActivity::stepLibraryScan() {
  if (!scan_.active) return false;

  if (!scan_.walkDone) {
    if (!scan_.activeDir && scan_.dirStack.empty()) {
      if (!applyLibraryScan()) return false;
      scan_.walkDone = true;
      return false;
    }
    scanDirectoryEntry();
    return false;
  }

  // Cover-thumb pass, one catalog entry per slice. The render task owns the same catalog, so
  // copy the entry under a non-blocking lock and do all SD/decode work after releasing it.
  const auto& metrics = UITheme::getInstance().getMetrics();
  int thumbH = gridCoverHeight_.load(std::memory_order_acquire);
  if (thumbH <= 0) {
    // Match renderBooksTab()/drawGridCell() exactly. The first scan slice can run before the
    // render task publishes its measurement; using homeCoverHeight here creates a valid BMP at
    // the wrong [HEIGHT], which the grid then cannot find.
    const int cellWidth = (renderer.getScreenWidth() - 2 * metrics.contentSidePadding) / GRID_COLS;
    const int coverWidth = cellWidth - 2 * COVER_PADDING;
    thumbH = coverWidth > 0 ? coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM : 0;
  }
  if (thumbH <= 0) thumbH = metrics.homeCoverHeight > 0 ? metrics.homeCoverHeight : 120;
  if (scan_.thumbIndex < recentBooks.size()) {
    RecentBook book;
    {
      RenderLock lock{RenderLock::Try{}};
      if (!lock.held()) return false;
      book = recentBooks[scan_.thumbIndex];
    }
    const auto publishBook = [this](const RecentBook& book) {
      bool changed = false;
      RenderLock lock{RenderLock::Try{}};
      if (!lock.held()) return false;
      const auto live = std::find_if(recentBooks.begin(), recentBooks.end(),
                                     [&book](const RecentBook& item) { return item.path == book.path; });
      if (live != recentBooks.end()) {
        if (!book.title.empty() && live->title != book.title) {
          live->title = book.title;
          changed = true;
        }
        if (!book.author.empty() && live->author != book.author) {
          live->author = book.author;
          changed = true;
        }
        if (!book.coverBmpPath.empty() && live->coverBmpPath != book.coverBmpPath) {
          live->coverBmpPath = book.coverBmpPath;
          changed = true;
        }
        if (changed) {
          if (shelvesLoaded) loadShelves();
          lastRendered.valid = false;
        }
      }
      lock.unlock();
      if (changed) requestUpdate();
      return true;
    };

    // The worker publishes by releasing busy only after the result is complete, so the loop can
    // consume this single slot without another mutex. A cancelled job leaves the cursor in place
    // and is retried after the next idle period; completed failures advance instead of looping.
    if (coverWorkerBusy_.load(std::memory_order_acquire)) return false;
    if (coverResult_.pending) {
      const bool matches = coverResult_.book.path == book.path;
      if (matches && coverResult_.hasGridThumb) {
        if (!publishBook(coverResult_.book)) return false;
        RECENT_BOOKS.updateBook(coverResult_.book.path, coverResult_.book.title, coverResult_.book.author,
                                coverResult_.book.coverBmpPath);
      }
      if (matches && (FsHelpers::hasEpubExtension(book.path) || FsHelpers::hasXtcExtension(book.path))) {
        recordIndexEntry(book.path, coverResult_.fileSize, coverResult_.modifiedStamp, thumbH,
                         coverResult_.hasGridThumb, coverResult_.coverKnownAbsent);
      }
      const bool completed = coverResult_.completed;
      coverResult_.pending = false;
      if (matches && completed) scan_.thumbIndex++;
      return false;
    }
    // A [HEIGHT]-templated path does NOT mean the thumb exists at the height this theme asks
    // for: switching themes changes homeCoverHeight, and skipping on "has a cover path" left
    // every EPUB in the Library without a cover until it was opened again (device report:
    // covers gone after switching to RoundedRaff). The manga pass already re-checks the
    // height; the lookup below does the same here, so only raw (non-templated) paths skip.
    const bool coverIsTemplate = book.coverBmpPath.find("[HEIGHT]") != std::string::npos;
    // .bmp counts too: pages that are already bitmaps still need a thumbnail, because drawing a
    // full-size dithered page into the cell comes out near-black (see BmpToBmpConverter). The
    // book-type gate matters now that .bmp is included -- an EPUB may carry a raw cover.bmp from
    // an older build and must not be treated as a manga folder.
    const bool isEpub = FsHelpers::hasEpubExtension(book.path);
    const bool isXtc = FsHelpers::hasXtcExtension(book.path);
    const bool isText = FsHelpers::hasTxtExtension(book.path) || FsHelpers::hasMarkdownExtension(book.path);
    const bool isMangaEntry = !isEpub && !isXtc && !isText;
    const bool coverIsRawImage =
        isMangaEntry && !book.coverBmpPath.empty() && !coverIsTemplate &&
        (FsHelpers::hasJpgExtension(book.coverBmpPath) || FsHelpers::hasPngExtension(book.coverBmpPath) ||
         FsHelpers::hasBmpExtension(book.coverBmpPath));
    // A manga templated by an EARLIER scan has to come back through here, and used to be skipped
    // for good: this branch only accepted raw paths, and the EPUB check below drops every
    // non-.epub entry. So the heights that scan happened to generate were the only ones a manga
    // ever got. Nothing else fills the gap -- HomeActivity::loadRecentCovers regenerates .epub
    // and .xtc thumbs only -- so the home card resolved its own height against a file nobody
    // would ever write (device log: "[LIB] File does not exist: .../manga_*/thumb_300.bmp").
    // Only the X4 hid it, by falling back to a live raw-JPEG decode; the X3's tighter heap
    // (52272-byte framebuffer, wider viewport) has nothing left for a 20KB JPEGDEC, which is why
    // manga covers were missing there and not here.
    const bool coverIsMangaTemplate = coverIsTemplate && book.coverBmpPath.rfind("/.crosspoint/manga_", 0) == 0;
    const bool mangaGridMissing =
        coverIsMangaTemplate && !thumbHeightValid(UITheme::getCoverThumbPath(book.coverBmpPath, thumbH), thumbH);
    const bool mangaHomeMissing =
        coverIsMangaTemplate && metrics.homeCoverHeight > 0 &&
        !thumbHeightValid(UITheme::getCoverThumbPath(book.coverBmpPath, metrics.homeCoverHeight),
                          metrics.homeCoverHeight);
    const bool mangaShelfMissing =
        coverIsMangaTemplate &&
        !thumbHeightValid(UITheme::getCoverThumbPath(book.coverBmpPath, SHELF_THUMB_HEIGHT), SHELF_THUMB_HEIGHT);
    const bool mangaThumbMissing = coverIsMangaTemplate && (mangaGridMissing || mangaHomeMissing || mangaShelfMissing);
    // Manga: the walk only recorded the raw page image; convert it here, where the pass is
    // idle-gated and cancellable, instead of freezing the walk.
    if (isMangaEntry && (book.coverBmpPath.empty() || coverIsRawImage || mangaThumbMissing)) {
      RenderLock lock{RenderLock::Try{}};
      if (!lock.held()) return false;
      if (auto* fcm = renderer.getFontCacheManager()) fcm->releaseAllFontMemory();
      lock.unlock();
      CoverJob job;
      job.book = book;
      job.gridHeight = thumbH;
      job.targetHeight =
          coverIsMangaTemplate
              ? (mangaGridMissing ? thumbH : (mangaHomeMissing ? metrics.homeCoverHeight : SHELF_THUMB_HEIGHT))
              : thumbH;
      if (!postCoverJob(std::move(job))) scan_.thumbIndex++;
      return false;
    }
    if ((!book.coverBmpPath.empty() && !coverIsTemplate) || (!isEpub && !isXtc)) {
      scan_.thumbIndex++;
      return false;
    }
    std::string cachePath = std::string("/.crosspoint/") + (isEpub ? "epub_" : "xtc_") +
                            std::to_string(std::hash<std::string>{}(book.path));
    std::string thumbPath = cachePath + "/thumb_" + std::to_string(thumbH) + ".bmp";

    // Index shortcut: a record whose size, modification stamp and cover height all still match
    // was verified by an earlier scan, so skip the file open entirely. Only books the index
    // does not vouch for pay for thumbHeightValid() -- that per-book open on every Library
    // visit is what made this pass expensive on a full card.
    uint32_t bookSize = 0, bookStamp = 0;
    {
      HalFile bf;
      if (Storage.openFileForRead("LIB", book.path, bf)) {
        bookSize = static_cast<uint32_t>(bf.size());
        bookStamp = bf.modifiedStamp();
      }
    }
    const uint32_t bookHash = static_cast<uint32_t>(std::hash<std::string>{}(book.path));
    const LibraryIndexEntry* indexed = findIndexEntry(bookHash);
    // The index knows a thumb WAS produced; it cannot know the file is still there. Trusting the
    // flag alone left three books on a test card with a cover the grid could never draw
    // (idxOk=1, file absent) -- and because the shortcut below re-records its own claim, that
    // state sustained itself across every later scan. Confirm with hasContent(), which still
    // skips the expensive part this shortcut exists for: the header parse and payload-length
    // check inside thumbHeightValid().
    //
    // hasContent() rather than exists() because a 0-byte file satisfied exists() and so let the
    // index validate its own claim against a husk: the grid published thumb_[HEIGHT].bmp as the
    // cover path, drawCoverThumbFilled() failed parseHeaders(), the placeholder was drawn, and
    // recordIndexEntry() wrote the same flag back -- a wrong entry that kept itself alive with
    // nothing logged. Generators no longer write such files, but cards already carry them.
    const bool indexSaysThumbOk = indexed && (indexed->flags & INDEX_FLAG_HAS_THUMB) && indexed->fileSize == bookSize &&
                                  indexed->modifiedStamp == bookStamp &&
                                  indexed->thumbHeight == static_cast<uint16_t>(thumbH) &&
                                  FsHelpers::hasContent("LIB", thumbPath);
    const bool gridThumbOk = indexSaysThumbOk || thumbHeightValid(thumbPath, thumbH);
    const std::string shelfThumbPath = cachePath + "/thumb_" + std::to_string(SHELF_THUMB_HEIGHT) + ".bmp";
    const bool shelfThumbOk = thumbHeightValid(shelfThumbPath, SHELF_THUMB_HEIGHT);
    // Height-checked, not just present: earlier builds bounded the thumb's WIDTH too, so a
    // wide cover produced a file that is shorter than its name claims and the grid drew it
    // with a white strip below. thumbHeightValid() sends those through the generator again.
    if (gridThumbOk && shelfThumbOk) {
      book.coverBmpPath = cachePath + "/thumb_[HEIGHT].bmp";
      recordIndexEntry(book.path, bookSize, bookStamp, thumbH, true);
      if (!publishBook(book)) return false;
      scan_.thumbIndex++;
      return false;
    }
    // The book has no cover image to render, established by a previous visit that actually
    // loaded it (INDEX_FLAG_NO_COVER; see Epub::hasCoverImage). Skipping here is what keeps a
    // coverless book from being re-parsed on every Library visit now that generateThumbBmp()
    // no longer drops a 0-byte file to shortcut itself. Guarded by the same size/stamp match as
    // the thumb shortcut, so replacing the file re-examines it -- and unlike the sentinel this
    // records a fact about the BOOK, which a failed conversion can never fake.
    if (indexed && (indexed->flags & INDEX_FLAG_NO_COVER) && indexed->fileSize == bookSize &&
        indexed->modifiedStamp == bookStamp) {
      scan_.thumbIndex++;
      return false;
    }
    // Coalesce the heap first: the cover decode needs a ~20KB contiguous block for the JPEG
    // decoder plus its MCU buffer, and on the X3 (larger viewport, larger font caches) the
    // largest free block can fall below that -- the decode then stops midway and produced a
    // streaked, half-black thumbnail (user report). Fonts reload lazily afterwards. Same step
    // the home screen already takes before generating XTC thumbs.
    RenderLock lock{RenderLock::Try{}};
    if (!lock.held()) return false;
    if (auto* fcm = renderer.getFontCacheManager()) fcm->releaseAllFontMemory();
    lock.unlock();
    if (!gridThumbOk) Storage.remove(thumbPath.c_str());
    if (!shelfThumbOk) Storage.remove(shelfThumbPath.c_str());
    CoverJob job;
    job.book = book;
    job.gridHeight = thumbH;
    job.targetHeight = gridThumbOk ? SHELF_THUMB_HEIGHT : thumbH;
    job.fileSize = bookSize;
    job.modifiedStamp = bookStamp;
    if (!postCoverJob(std::move(job))) {
      recordIndexEntry(book.path, bookSize, bookStamp, thumbH, false);
      scan_.thumbIndex++;
    }
    return false;
  }

  scan_.active = false;
  return true;
}

void RecentBooksActivity::scanDirectoryEntry() {
  if (!scan_.activeDir) {
    scan_.activeDirPath = std::move(scan_.dirStack.back());
    scan_.dirStack.pop_back();
    scan_.activeDir = Storage.open(scan_.activeDirPath.c_str());
    if (!scan_.activeDir || !scan_.activeDir.isDirectory()) {
      scan_.activeDir.close();
      scan_.activeDirPath.clear();
      return;
    }
    scan_.activeDir.rewindDirectory();
  }

  auto file = scan_.activeDir.openNextFile();
  if (!file) {
    scan_.activeDir.close();
    scan_.activeDirPath.clear();
    return;
  }

  file.getName(scan_.nameBuf.data(), scan_.nameBuf.size());
  const char* name = scan_.nameBuf.data();
  if (name[0] == '.' || strcmp(name, "System Volume Information") == 0 || strcmp(name, "dict") == 0) return;

  std::string fullPath = scan_.activeDirPath;
  if (fullPath.back() != '/') fullPath += '/';
  fullPath += name;

  if (file.isDirectory()) {
    if (!Storage.exists((fullPath + "/panels.idx").c_str())) {
      scan_.dirStack.push_back(std::move(fullPath));
      return;
    }
    RecentBook book{fullPath, name, "", ""};
    const auto cached = std::find_if(recentBooks.begin(), recentBooks.end(),
                                     [&fullPath](const RecentBook& item) { return item.path == fullPath; });
    if (cached != recentBooks.end()) book = *cached;
    scan_.results.push_back(std::move(book));
    return;
  }

  const std::string_view filename{name};
  if ((!FsHelpers::hasEpubExtension(filename) && !FsHelpers::hasXtcExtension(filename) &&
       !FsHelpers::hasTxtExtension(filename) && !FsHelpers::hasMarkdownExtension(filename)) ||
      isCrashReportFile(name)) {
    return;
  }

  const auto dot = filename.find_last_of('.');
  RecentBook book{fullPath, std::string(dot == std::string_view::npos ? filename : filename.substr(0, dot)), "", ""};
  const auto cached = std::find_if(recentBooks.begin(), recentBooks.end(),
                                   [&fullPath](const RecentBook& item) { return item.path == fullPath; });
  if (cached != recentBooks.end()) book = *cached;
  scan_.results.push_back(std::move(book));
}

bool RecentBooksActivity::applyLibraryScan() {
  RenderLock lock{RenderLock::Try{}};
  if (!lock.held()) return false;

  // Cached entries whose files vanished drop out; recents remain first without building a
  // second full catalog.
  mergeRecentBooks(scan_.results, RECENT_BOOKS.getBooks());

  bool changed = scan_.results.size() != recentBooks.size();
  if (!changed) {
    for (size_t i = 0; i < scan_.results.size(); i++) {
      const auto& fresh = scan_.results[i];
      const auto& old = recentBooks[i];
      if (fresh.path != old.path || fresh.title != old.title || fresh.author != old.author ||
          fresh.coverBmpPath != old.coverBmpPath) {
        changed = true;
        break;
      }
    }
  }

  recentBooks = std::move(scan_.results);
  if (changed) {
    markAllProgressPending();
    if (shelvesLoaded) loadShelves();
    lastRendered.valid = false;
    LOG_DBG("RBA", "Library scan applied: %u books", static_cast<unsigned>(recentBooks.size()));
  }
  lock.unlock();
  if (changed) requestUpdate();
  return true;
}

void RecentBooksActivity::finishLibraryScan() {
  saveLibraryIndex();
  RecentBooksStore::saveBooksToPath(recentBooks, LIBRARY_CACHE_JSON);
}

void RecentBooksActivity::loadBookProgress() {
  // Progress is filled progressively from loop() -- ~5 file reads per book made the old
  // upfront pass a visible chunk of the Library open time.
  markAllProgressPending();
}

void RecentBooksActivity::markAllProgressPending() {
  bookProgress.clear();
  BookProgress pending;
  pending.percent = PROGRESS_PENDING;
  bookProgress.resize(recentBooks.size(), pending);
}

void RecentBooksActivity::warmOnePendingProgress() {
  size_t index = 0;
  std::string path;
  {
    RenderLock lock{RenderLock::Try{}};
    if (!lock.held()) return;
    while (index < bookProgress.size() && index < recentBooks.size() &&
           bookProgress[index].percent != PROGRESS_PENDING) {
      index++;
    }
    if (index >= bookProgress.size() || index >= recentBooks.size()) return;
    path = recentBooks[index].path;
  }

  const int percent = readProgressPercent(path);

  RenderLock lock{RenderLock::Try{}};
  if (!lock.held()) return;
  if (recentBooks[index].path == path && bookProgress[index].percent == PROGRESS_PENDING) {
    bookProgress[index].percent = percent;
  }
  // No requestUpdate: visible entries are still filled synchronously during their render.
}

void RecentBooksActivity::loadShelves() {
  shelvesLoaded = true;
  shelves.clear();

  for (const auto& book : recentBooks) {
    std::string folder = FsHelpers::extractFolderPath(book.path);
    size_t lastSlash = folder.find_last_of('/');
    std::string name =
        (lastSlash != std::string::npos && lastSlash < folder.size() - 1) ? folder.substr(lastSlash + 1) : folder;
    if (folder == "/") name = "Unsorted";

    const auto shelf =
        std::find_if(shelves.begin(), shelves.end(), [&folder](const auto& s) { return s.folderPath == folder; });
    if (shelf != shelves.end()) {
      shelf->bookCount++;
      if (shelf->coverBmpPath.empty() && !book.coverBmpPath.empty()) {
        shelf->coverBmpPath = book.coverBmpPath;
      }
    } else {
      ShelfInfo fresh;
      fresh.folderPath = folder;
      fresh.folderName = name;
      fresh.coverBmpPath = book.coverBmpPath;
      fresh.bookCount = 1;
      shelves.push_back(std::move(fresh));
    }
  }

  std::sort(shelves.begin(), shelves.end(),
            [](const ShelfInfo& a, const ShelfInfo& b) { return a.folderName < b.folderName; });

  // The idle thumbnail pass creates this size. Merely resolving the path keeps shelf loading
  // free of SD reads and image decoding.
  for (auto& shelf : shelves) {
    if (!shelf.coverBmpPath.empty() && shelf.coverBmpPath.find("[HEIGHT]") != std::string::npos) {
      shelf.shelfThumbPath = UITheme::getCoverThumbPath(shelf.coverBmpPath, SHELF_THUMB_HEIGHT);
    }
  }
}

void RecentBooksActivity::loadShelfBooks(const std::string& folderPath) {
  lastRendered.valid = false;  // content changing under the frame -> next render must be full
  shelfBooks.clear();
  shelfBookProgress.clear();

  for (const auto& book : recentBooks) {
    if (FsHelpers::extractFolderPath(book.path) != folderPath) continue;
    shelfBooks.push_back(ShelfBook{book.path, book.title, book.coverBmpPath});
  }

  std::sort(shelfBooks.begin(), shelfBooks.end(),
            [](const ShelfBook& a, const ShelfBook& b) { return a.title < b.title; });

  shelfBookProgress.resize(shelfBooks.size(), BookProgress{PROGRESS_PENDING});
}

int RecentBooksActivity::readProgressPercent(const std::string& bookPath) const {
  std::string cachePath;
  if (FsHelpers::hasEpubExtension(bookPath)) {
    cachePath = "/.crosspoint/epub_" + std::to_string(std::hash<std::string>{}(bookPath));
  } else if (FsHelpers::hasXtcExtension(bookPath)) {
    return XtcProgress::percentForBook(bookPath);
  } else if (manga::MangaBook::isMangaFolder(bookPath)) {
    std::string mangaCachePath = "/.crosspoint/manga_" + std::to_string(std::hash<std::string>{}(bookPath));
    HalFile f;
    if (!Storage.openFileForRead("LIB", mangaCachePath + "/progress.bin", f)) return 0;
    uint8_t data[4];
    if (f.read(data, 4) != 4) return 0;
    uint32_t currentPage = data[0] | (data[1] << 8) | (data[2] << 16) | (data[3] << 24);
    HalFile idxFile;
    if (!Storage.openFileForRead("LIB", bookPath + "/panels.idx", idxFile)) return 0;
    uint8_t hdr[8];
    if (idxFile.read(hdr, 8) != 8) return 0;
    uint32_t totalPages = hdr[4] | (hdr[5] << 8) | (hdr[6] << 16) | (hdr[7] << 24);
    if (totalPages == 0) return 0;
    int pct = static_cast<int>((static_cast<float>(currentPage) / static_cast<float>(totalPages)) * 100.0f + 0.5f);
    return std::clamp(pct, 0, 100);
  } else {
    return -1;
  }

  if (FsHelpers::hasEpubExtension(bookPath)) {
    const int pct = EpubProgress::percentFromCache(cachePath, "LIB");
    return pct < 0 ? 0 : pct;
  }
  return -1;
}

void RecentBooksActivity::touchScreenTrampoline(UiScreen& screen, void* user) {
  static_cast<RecentBooksActivity*>(user)->buildTouchTargets(screen);
}

void RecentBooksActivity::touchActionTrampoline(const fui::ActionEvent& event, void* user) {
  static_cast<RecentBooksActivity*>(user)->onTouchAction(event);
}

void RecentBooksActivity::onTouchAction(const fui::ActionEvent& event) {
  switch (event.action) {
    case ACTION_TAB:
      if (event.value >= 0 && event.value < TAB_COUNT && selectedTab != event.value) {
        selectedTab = event.value;
        contentIndex = 0;
        scrollRow = 0;
        if (selectedTab == 1 && !shelvesLoaded) loadShelves();
        requestUpdate();
      }
      break;
    case ACTION_BOOK:
      if (event.longPress) {
        if (event.value >= 0 && event.value < static_cast<int>(recentBooks.size())) {
          app.clearTapFlash();
          showBookStats(recentBooks[event.value].path, recentBooks[event.value].title);
        }
      } else {
        openRecentBook(event.value);
      }
      break;
    case ACTION_SHELF:
      openShelf(event.value);
      break;
    case ACTION_SHELF_BOOK:
      if (event.longPress) {
        if (event.value >= 0 && event.value < static_cast<int>(shelfBooks.size())) {
          app.clearTapFlash();
          showBookStats(shelfBooks[event.value].path, shelfBooks[event.value].title);
        }
      } else {
        openShelfBook(event.value);
      }
      break;
    default:
      break;
  }
}

bool RecentBooksActivity::handleTouchTabTap() {
  if (openShelfIndex >= 0 || !mappedInput.hasTouch()) return false;
  int tx = 0;
  int ty = 0;
  if (!mappedInput.wasScreenTapped(tx, ty)) return false;

  const auto& metrics = UITheme::getInstance().getMetrics();
  const Rect tabRect{0, metrics.topPadding + metrics.headerHeight, renderer.getScreenWidth(), metrics.tabBarHeight};
  touchTabs_.clear();
  touchTabs_.push_back({tr(STR_TAB_BOOKS), selectedTab == 0});
  touchTabs_.push_back({tr(STR_TAB_SHELVES), selectedTab == 1});

  int touchedTab = -1;
  if (!GUI.tabIndexFromPoint(renderer, tabRect, touchTabs_, tx, ty, touchedTab)) return false;
  lastInputMs = millis();
  coverWorkerCancelRequested_ = true;
  if (touchedTab == selectedTab) return true;

  selectedTab = touchedTab;
  contentIndex = 0;
  scrollRow = 0;
  if (selectedTab == 1 && !shelvesLoaded) loadShelves();
  requestUpdate();
  return true;
}

bool RecentBooksActivity::handleTouchScroll() {
  if (!mappedInput.hasTouch()) return false;
  const auto swipe = mappedInput.wasSwipe();
  if (swipe != MappedInputManager::SwipeDir::Up && swipe != MappedInputManager::SwipeDir::Down) return false;

  const auto& metrics = UITheme::getInstance().getMetrics();
  const int pageHeight = renderer.getScreenHeight();
  const int delta = swipe == MappedInputManager::SwipeDir::Up ? 1 : -1;
  bool moved = false;

  if (openShelfIndex >= 0) {
    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int gridWidth = renderer.getScreenWidth() - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    const int totalRows = (static_cast<int>(shelfBooks.size()) + GRID_COLS - 1) / GRID_COLS;
    const int next = std::clamp(shelfScrollRow + delta, 0, std::max(0, totalRows - visibleRows));
    moved = next != shelfScrollRow;
    shelfScrollRow = next;
    shelfContentIndex = -1;
  } else if (selectedTab == 0) {
    const int tabBarY = metrics.topPadding + metrics.headerHeight;
    const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int gridWidth = renderer.getScreenWidth() - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    const int totalRows = (static_cast<int>(recentBooks.size()) + GRID_COLS - 1) / GRID_COLS;
    const int next = std::clamp(scrollRow + delta, 0, std::max(0, totalRows - visibleRows));
    moved = next != scrollRow;
    scrollRow = next;
    contentIndex = 0;
  } else {
    const int tabBarY = metrics.topPadding + metrics.headerHeight;
    const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int rowHeight = metrics.listWithSubtitleRowHeight;
    const int visibleItems = std::max(1, contentHeight / rowHeight);
    const int next = std::clamp(scrollRow + delta, 0, std::max(0, static_cast<int>(shelves.size()) - visibleItems));
    moved = next != scrollRow;
    scrollRow = next;
    contentIndex = 0;
  }

  lastInputMs = millis();
  coverWorkerCancelRequested_ = true;
  if (moved) requestUpdate();
  return true;
}

void RecentBooksActivity::openShelf(const int shelfIndex) {
  if (shelfIndex < 0 || shelfIndex >= static_cast<int>(shelves.size())) return;
  LOG_DBG("RBA", "Opening shelf: %s", shelves[shelfIndex].folderPath.c_str());
  openShelfIndex = shelfIndex;
  shelfContentIndex = 0;
  shelfScrollRow = 0;
  loadShelfBooks(shelves[shelfIndex].folderPath);
  requestUpdate();
}

void RecentBooksActivity::openRecentBook(const int bookIndex) {
  if (bookIndex < 0 || bookIndex >= static_cast<int>(recentBooks.size())) return;
  app.clearTapFlash();
  LOG_DBG("RBA", "Selected recent book: %s", recentBooks[bookIndex].path.c_str());
  onSelectBook(recentBooks[bookIndex].path);
}

void RecentBooksActivity::openShelfBook(const int bookIndex) {
  if (bookIndex < 0 || bookIndex >= static_cast<int>(shelfBooks.size())) return;
  app.clearTapFlash();
  LOG_DBG("RBA", "Selected shelf book: %s", shelfBooks[bookIndex].path.c_str());
  onSelectBook(shelfBooks[bookIndex].path);
}

void RecentBooksActivity::onEnter() {
  Activity::onEnter();
  resetUi();
  app.on(ACTION_TAB, &RecentBooksActivity::touchActionTrampoline, this);
  app.on(ACTION_BOOK, &RecentBooksActivity::touchActionTrampoline, this);
  app.on(ACTION_SHELF, &RecentBooksActivity::touchActionTrampoline, this);
  app.on(ACTION_SHELF_BOOK, &RecentBooksActivity::touchActionTrampoline, this);
  app.setScreen(&RecentBooksActivity::touchScreenTrampoline, this);
  touchTabs_.reserve(TAB_COUNT);
  lastInputMs = millis();

  if (RECENT_BOOKS.pruneMissing()) {
    RECENT_BOOKS.saveToFile();
  }

  loadRecentBooks();
  loadBookProgress();
  shelvesLoaded = false;
  startCoverWorker();
  startLibraryScan();

  selectedTab = 0;
  contentIndex = 0;
  scrollRow = 0;
  openShelfIndex = -1;
  requestUpdate();
}

void RecentBooksActivity::onExit() {
  // ActivityManager may hold RenderLock here. The worker never takes it; its cancellation probe
  // sees the held lock, drops any partial thumbnail and exits before activity state is cleared.
  stopCoverWorker();
  Activity::onExit();
  scan_ = LibraryScanState{};
  libraryIndex_.clear();
  recentBooks.clear();
  bookProgress.clear();
  shelves.clear();
  shelfBooks.clear();
  shelfBookProgress.clear();
}

void RecentBooksActivity::loop() {
  // Raw state catches the press before any early return below and cancels background SD/decode
  // work even when the debounced edge has not been emitted yet.
  if (mappedInput.anyButtonDownRaw()) {
    lastInputMs = millis();
    coverWorkerCancelRequested_ = true;
  }

  if (handleTouchTabTap()) return;
  if (handleTouchScroll()) return;
  if (routeLibraryTouch()) return;

  const auto& metrics = UITheme::getInstance().getMetrics();
  const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
  const int contentHeight =
      renderer.getScreenHeight() - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  const int pageItems = std::max(1, contentHeight / metrics.listWithSubtitleRowHeight);

  if (openShelfIndex >= 0) {
    if (mappedInput.wasPressed(MappedInputManager::Button::Back)) {
      openShelfIndex = -1;
      shelfBooks.clear();
      shelfBookProgress.clear();
      requestUpdate();
      return;
    }

    // Needed here too: this block returns before the copy below, so without it the release
    // ending a long press would fall through and open the book.
    if (longPressFired) {
      if (!mappedInput.isPressed(MappedInputManager::Button::Confirm)) {
        longPressFired = false;
      }
      return;
    }

    if (shelfContentIndex < static_cast<int>(shelfBooks.size())) {
      // Shelves are where manga folders are browsed; without this they had no route to stats.
      if (mappedInput.isPressed(MappedInputManager::Button::Confirm) && mappedInput.getHeldTime() >= LONG_PRESS_MS) {
        longPressFired = true;
        showBookStats(shelfBooks[shelfContentIndex].path, shelfBooks[shelfContentIndex].title);
        return;
      }
      if (mappedInput.wasReleased(MappedInputManager::Button::Confirm) && mappedInput.getHeldTime() < LONG_PRESS_MS) {
        openShelfBook(shelfContentIndex);
        return;
      }
    }

    const int shelfItemCount = static_cast<int>(shelfBooks.size());
    if (shelfItemCount > 0) {
      buttonNavigator.onNextRelease([this, shelfItemCount] {
        shelfContentIndex = ButtonNavigator::nextIndex(shelfContentIndex, shelfItemCount);
        requestUpdate();
      });
      buttonNavigator.onPreviousRelease([this, shelfItemCount] {
        shelfContentIndex = ButtonNavigator::previousIndex(shelfContentIndex, shelfItemCount);
        requestUpdate();
      });
    }
    return;
  }

  bool hasChangedTab = false;

  if (mappedInput.wasPressed(MappedInputManager::Button::Confirm)) {
    if (contentIndex == 0) {
      selectedTab = (selectedTab + 1) % TAB_COUNT;
      hasChangedTab = true;
      if (selectedTab == 1 && !shelvesLoaded) loadShelves();
      requestUpdate();
    } else {
      const int itemIdx = contentIndex - 1;
      if (selectedTab == 0) {
        // Nothing here: Recents books open on RELEASE (below). Opening on the press edge
        // returns from loop() at once, so getHeldTime() never reached LONG_PRESS_MS and the
        // long press was unreachable (803fcf3c until now). Shelves keep press-to-act: no
        // long press to make room for.
        (void)itemIdx;
      } else {
        if (itemIdx < static_cast<int>(shelves.size())) {
          openShelf(itemIdx);
          return;
        }
      }
    }
  }

  if (longPressFired) {
    if (!mappedInput.isPressed(MappedInputManager::Button::Confirm)) {
      longPressFired = false;
    }
    return;
  }

  if (selectedTab == 0 && contentIndex > 0) {
    const int itemIdx = contentIndex - 1;
    if (itemIdx < static_cast<int>(recentBooks.size())) {
      // Fires while still held, so the gesture completes without waiting for release.
      if (mappedInput.isPressed(MappedInputManager::Button::Confirm) && mappedInput.getHeldTime() >= LONG_PRESS_MS) {
        longPressFired = true;
        showBookStats(recentBooks[itemIdx].path, recentBooks[itemIdx].title);
        return;
      }
      // The latch above swallows a long press's release, so stats never also opens the book.
      if (mappedInput.wasReleased(MappedInputManager::Button::Confirm) && mappedInput.getHeldTime() < LONG_PRESS_MS) {
        openRecentBook(itemIdx);
        return;
      }
    }
  }

  // Button-era touch swipes are handled above as viewport scrolls. Keep this
  // legacy cursor step only as a fallback for any non-touch swipe source.
  const auto swipe = mappedInput.wasSwipe();
  if (swipe == MappedInputManager::SwipeDir::Up || swipe == MappedInputManager::SwipeDir::Down) {
    const int totalItems = getContentItemCount() + 1;
    const int delta = (swipe == MappedInputManager::SwipeDir::Up) ? GRID_COLS : -GRID_COLS;
    const int moved = std::clamp(contentIndex + delta, 0, std::max(0, totalItems - 1));
    if (moved != contentIndex) {
      contentIndex = moved;
      requestUpdate();
    }
    return;
  }

  if (mappedInput.wasPressed(MappedInputManager::Button::Back)) {
    if (contentIndex > 0) {
      contentIndex = 0;
      scrollRow = 0;
      requestUpdate();
    } else {
      onGoHome();
    }
    return;
  }

  const int totalItems = getContentItemCount() + 1;

  buttonNavigator.onNextRelease([this, totalItems] {
    contentIndex = ButtonNavigator::nextIndex(contentIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onPreviousRelease([this, totalItems] {
    contentIndex = ButtonNavigator::previousIndex(contentIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onNextContinuous([this, &hasChangedTab] {
    hasChangedTab = true;
    selectedTab = ButtonNavigator::nextIndex(selectedTab, TAB_COUNT);
    requestUpdate();
  });

  buttonNavigator.onPreviousContinuous([this, &hasChangedTab] {
    hasChangedTab = true;
    selectedTab = ButtonNavigator::previousIndex(selectedTab, TAB_COUNT);
    requestUpdate();
  });

  if (hasChangedTab) {
    contentIndex = (contentIndex == 0) ? 0 : 1;
    scrollRow = 0;
    if (selectedTab == 1 && !shelvesLoaded) loadShelves();
  }

  // Background work, one slice per tick: re-scan the card (stale-while-revalidate), post one
  // cover job at a time, and fill pending progress percentages. The worker cancels as soon as
  // input or rendering needs the CPU/SD card.
  if (mappedInput.wasAnyPressed()) lastInputMs = millis();
  if (scan_.active) {
    // Both phases are idle-gated now. The walk was assumed cheap ("one directory listing"),
    // but a manga folder holds hundreds of page files and listing one costs seconds on SD
    // (measured: a 2220ms loop gap) -- a click landing inside that window is never even sampled
    // as a press, so the Library felt completely dead while it scanned.
    const uint32_t idleBeforeWorkMs = scan_.walkDone ? THUMB_IDLE_MS : 700;
    if (millis() - lastInputMs > idleBeforeWorkMs && !RenderLock::peek()) {
      const bool done = stepLibraryScan();
      if (done) finishLibraryScan();
    }
  } else if (millis() - lastInputMs > 700 && !mappedInput.anyButtonDownRaw()) {
    warmOnePendingProgress();
  }
}

void RecentBooksActivity::showBookStats(const std::string& path, const std::string& title) {
  auto handler = [this](const ActivityResult&) {
    lastRendered.valid = false;  // stats painted over the frame; a partial redraw would smear
  };

  startActivityForResult(std::make_unique<BookStatsActivity>(renderer, mappedInput, path, title), std::move(handler));
}

void RecentBooksActivity::drawGridSelectionBorder(const int cellX, const int cellY, const int cellWidth,
                                                  const int cellHeight, const bool on) {
  (void)cellHeight;
  const int coverWidth = cellWidth - 2 * COVER_PADDING;
  const int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  const int coverX = cellX + COVER_PADDING;
  const int coverY = cellY + COVER_PADDING;
  // Two nested 1px rects = a 2px ring at offsets -2/-3 from the cover box: a 1px white gap
  // separates it from the cover's own 1px outline, and it stays clear of the progress label
  // below (labelY = cover bottom + CELL_TEXT_GAP).
  renderer.drawRect(coverX - 2, coverY - 2, coverWidth + 4, coverHeight + 4, on);
  renderer.drawRect(coverX - 3, coverY - 3, coverWidth + 6, coverHeight + 6, on);
}

void RecentBooksActivity::drawGridCell(const int cellX, const int cellY, const int cellWidth, const int cellHeight,
                                       const std::string& coverBmpPath, const std::string& title,
                                       const int progressPercent, const bool selected, const bool drawTitle) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int coverWidth = cellWidth - 2 * COVER_PADDING;
  const int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  // Request the thumb at the size it is drawn at: a theme-sized thumb (300px, 400px in
  // Classic) scaled into this cell cost ~2.5s per cover in software scaling.
  const int thumbHeight = coverHeight;
  gridCoverHeight_.store(coverHeight, std::memory_order_release);
  const int lineHeight = renderer.getLineHeight(SMALL_FONT_ID);
  const int coverX = cellX + COVER_PADDING;
  const int coverY = cellY + COVER_PADDING;

  if (selected) {
    drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, true);
  }

  bool hasCover = false;
  if (!coverBmpPath.empty()) {
    const std::string coverPath = UITheme::getCoverThumbPath(coverBmpPath, thumbHeight);
    // Shared helper: manga covers are raw page images (JPG/PNG), EPUB/XTC covers pre-cropped
    // BMP thumbnails. Both fill the cell and crop the overflow rather than letterboxing.
    hasCover = UITheme::drawCoverThumbFilled(renderer, coverPath, coverX, coverY, coverWidth, coverHeight,
                                             /*allowRawDecode=*/false);
  }

  renderer.drawRect(coverX, coverY, coverWidth, coverHeight, true);

  if (!hasCover) {
    renderer.drawIcon(CoverIcon, coverX + (coverWidth - 32) / 2, coverY + (coverHeight - 32) / 2, 32);
    auto titleLines = renderer.wrappedText(SMALL_FONT_ID, title.c_str(), coverWidth - 8, 3);
    int textY = coverY + (coverHeight - 32) / 2 + 36;
    for (const auto& line : titleLines) {
      if (textY + lineHeight > coverY + coverHeight) break;
      const int textW = renderer.getTextWidth(SMALL_FONT_ID, line.c_str());
      const int textX = coverX + (coverWidth - textW) / 2;
      renderer.drawText(SMALL_FONT_ID, textX, textY, line.c_str(), true);
      textY += lineHeight;
    }
  }

  // Progress badge on the cover (top-right, white on black): "NEW" for unstarted books,
  // "Read" for finished ones, else the percentage. progressPercent < 0 means the idle-gated
  // progress pass hasn't reached this book yet -- draw nothing rather than a wrong badge.
  if (progressPercent >= 0) {
    char badgeBuf[8];
    if (progressPercent <= 0) {
      snprintf(badgeBuf, sizeof(badgeBuf), "%s", tr(STR_BOOK_BADGE_NEW));
    } else if (progressPercent >= 100) {
      snprintf(badgeBuf, sizeof(badgeBuf), "%s", tr(STR_BOOK_BADGE_READ));
    } else {
      snprintf(badgeBuf, sizeof(badgeBuf), "%d%%", progressPercent);
    }
    const int badgeTextW = renderer.getTextWidth(SMALL_FONT_ID, badgeBuf);
    const int badgeH = renderer.getLineHeight(SMALL_FONT_ID) + 4;
    const int badgeW = badgeTextW + 12;
    const int badgeX = coverX + coverWidth - badgeW;
    const int badgeY = coverY;
    // Black fill with a rounded bottom-left corner; pixels outside the arc stay untouched so
    // the cover shows through the corner notch.
    constexpr int badgeR = 4;
    renderer.fillRect(badgeX + badgeR, badgeY, badgeW - badgeR, badgeH, true);
    renderer.fillRect(badgeX, badgeY, badgeR, badgeH - badgeR, true);
    const int arcCx = badgeX + badgeR;
    const int arcCy = badgeY + badgeH - 1 - badgeR;
    for (int dy = 0; dy <= badgeR; dy++) {
      for (int dx = 0; dx <= badgeR; dx++) {
        const int d2 = dx * dx + dy * dy;
        if (d2 > badgeR * badgeR) continue;
        // Outermost ring of the arc is white so it joins the white edge lines below.
        renderer.drawPixel(arcCx - dx, arcCy + dy, d2 < (badgeR - 1) * (badgeR - 1));
      }
    }
    // White border on the two exposed edges (left + bottom); top/right sit on the cover edge.
    renderer.drawLine(badgeX, badgeY, badgeX, arcCy, false);
    renderer.drawLine(arcCx, badgeY + badgeH - 1, badgeX + badgeW - 1, badgeY + badgeH - 1, false);
    renderer.drawText(SMALL_FONT_ID, badgeX + 6, badgeY + 2, badgeBuf, false);
  }

  // Title below the cover, single line, ellipsis-truncated. The peek row skips this: its
  // title band lies under the button hints, so measuring/truncating it would be wasted work.
  const int labelY = coverY + coverHeight + CELL_TEXT_GAP;
  if (drawTitle && !title.empty()) {
    const std::string line = renderer.truncatedText(SMALL_FONT_ID, title.c_str(), coverWidth);
    renderer.drawText(SMALL_FONT_ID, coverX, labelY, line.c_str(), true);
  }
}

// Read the progress for the visible window's pending entries NOW (bounded: <=9 small reads).
// The deferred background pass still covers everything else; it just never gets to trigger a
// second full-screen refresh for cells the user is currently looking at.
void RecentBooksActivity::fillPageProgressNow(std::vector<BookProgress>& progress, const std::vector<RecentBook>* books,
                                              const std::vector<ShelfBook>* sBooks, const int firstIdx,
                                              const int lastIdx) {
  for (int i = firstIdx; i >= 0 && i <= lastIdx && i < static_cast<int>(progress.size()); i++) {
    if (progress[i].percent != PROGRESS_PENDING) continue;
    const std::string& path = books ? (*books)[i].path : (*sBooks)[i].path;
    progress[i].percent = readProgressPercent(path);
  }
}

void RecentBooksActivity::renderBooksTab(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (recentBooks.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_RECENT_BOOKS));
    return;
  }

  const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
  const int cellWidth = gridWidth / GRID_COLS;
  const int cellHeight = getCellHeight(cellWidth);
  const int rowStride = cellHeight + GRID_ROW_GAP;
  const int visibleRows = getVisibleRows(cellHeight, contentHeight);
  const int bookCount = static_cast<int>(recentBooks.size());
  const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;
  const int selectedItem = contentIndex - 1;

  if (selectedItem >= 0) {
    const int selectedRow = selectedItem / GRID_COLS;
    if (selectedRow < scrollRow) scrollRow = selectedRow;
    if (selectedRow >= scrollRow + visibleRows) scrollRow = selectedRow - visibleRows + 1;
  }
  scrollRow = std::clamp(scrollRow, 0, std::max(0, totalRows - visibleRows));

  // One extra row peeks behind the button bar as a "more below" hint (covers and badges show;
  // the hint bar overdraws the bottom). Its titles sit fully under the hints, so they are
  // never drawn or measured.
  const int renderRows = std::min(totalRows - scrollRow, visibleRows + 1);
  const int firstIdx = scrollRow * GRID_COLS;
  const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
  const int titledLastIdx = std::min(firstIdx + visibleRows * GRID_COLS, bookCount) - 1;

  // Fill the visible window's progress badges synchronously (max 9 books, ~2 small reads each)
  // so the first paint is already correct -- the deferred background pass caused a SECOND full
  // e-ink refresh right after opening, which read as sluggishness.
  fillPageProgressNow(bookProgress, &recentBooks, nullptr, firstIdx, lastIdx);

  // Prewarm titles for the full rows only (the peek row's titles are never drawn).
  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int idx = firstIdx; idx <= titledLastIdx; idx++) {
      prewarmBuf += recentBooks[idx].title;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(SMALL_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::REGULAR);
  }

  for (int idx = firstIdx; idx <= lastIdx; idx++) {
    const int local = idx - firstIdx;
    const int col = local % GRID_COLS;
    const int row = local / GRID_COLS;
    const int cellX = metrics.contentSidePadding + col * cellWidth;
    const int cellY = contentTop + row * rowStride;
    const int pct = idx < static_cast<int>(bookProgress.size()) ? bookProgress[idx].percent : -1;
    drawGridCell(cellX, cellY, cellWidth, cellHeight, recentBooks[idx].coverBmpPath, recentBooks[idx].title, pct,
                 idx == selectedItem, /*drawTitle=*/idx <= titledLastIdx);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required (FontDecompressor's page-slot pool
  // is small and shared globally; an unreleased prewarm permanently starves every other screen).
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
  drawGridScrollBar(contentTop, contentHeight, totalRows, visibleRows, scrollRow);
}

void RecentBooksActivity::drawShelfRow(const int shelfIdx, const int itemY, const bool selected) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();
  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int chevronMargin = 15;
  const auto& shelf = shelves[shelfIdx];

  if (selected) {
    renderer.fillRoundedRect(metrics.contentSidePadding - 6, itemY - 4, pageWidth - 2 * metrics.contentSidePadding + 12,
                             rowHeight + 8, SELECTION_RADIUS, Color::LightGray);
  }

  int thumbX = metrics.contentSidePadding + 4;
  int thumbY = itemY + (rowHeight - SHELF_THUMB_HEIGHT) / 2;

  bool hasThumb = false;
  // The shelf-height thumbnail (generated in loadShelves) renders 1:1, avoiding
  // the bitmap downscaler that produces all-black at heavy reductions.
  if (!shelf.shelfThumbPath.empty()) {
    HalFile file;
    if (Storage.openFileForRead("LIB", shelf.shelfThumbPath, file)) {
      Bitmap bitmap(file);
      if (bitmap.parseHeaders() == BmpReaderError::Ok) {
        // Center the (already small) thumb in the slot; no scaling needed.
        const int bw = bitmap.getWidth();
        const int bh = bitmap.getHeight();
        const int dx = thumbX + (SHELF_THUMB_WIDTH - bw) / 2;
        const int dy = thumbY + (SHELF_THUMB_HEIGHT - bh) / 2;
        renderer.drawBitmap(bitmap, dx, dy, bw, bh);
        hasThumb = true;
      }
      file.close();
    }
  }

  if (!hasThumb) {
    renderer.drawRect(thumbX, thumbY, SHELF_THUMB_WIDTH, SHELF_THUMB_HEIGHT, true);
  }

  const int textX = thumbX + SHELF_THUMB_WIDTH + 12;
  const int smallLH = renderer.getLineHeight(SMALL_FONT_ID);
  const int nameY = itemY + rowHeight / 2 - smallLH;

  renderer.drawText(UI_10_FONT_ID, textX, nameY, shelf.folderName.c_str(), true, EpdFontFamily::BOLD);

  char countBuf[32];
  if (shelf.bookCount == 1) {
    snprintf(countBuf, sizeof(countBuf), "%s", tr(STR_SHELF_BOOK_COUNT_1));
  } else {
    snprintf(countBuf, sizeof(countBuf), tr(STR_SHELF_BOOK_COUNT_N), shelf.bookCount);
  }
  renderer.drawText(SMALL_FONT_ID, textX, nameY + smallLH + 1, countBuf, true);

  const int chevronSize = 6;
  const int chevronX = pageWidth - metrics.contentSidePadding - chevronMargin;
  const int chevronY = itemY + rowHeight / 2;
  renderer.drawLine(chevronX, chevronY - chevronSize, chevronX + chevronSize, chevronY, true);
  renderer.drawLine(chevronX + chevronSize, chevronY, chevronX, chevronY + chevronSize, true);
  renderer.drawLine(chevronX + 1, chevronY - chevronSize, chevronX + chevronSize + 1, chevronY, true);
  renderer.drawLine(chevronX + chevronSize + 1, chevronY, chevronX + 1, chevronY + chevronSize, true);
}

void RecentBooksActivity::renderShelvesTab(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (shelves.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_SHELVES));
    return;
  }

  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int visibleItems = std::max(1, contentHeight / rowHeight);
  const int selectedItem = contentIndex - 1;
  const int shelfCount = static_cast<int>(shelves.size());

  if (selectedItem >= 0) {
    if (selectedItem < scrollRow) scrollRow = selectedItem;
    if (selectedItem >= scrollRow + visibleItems) scrollRow = selectedItem - visibleItems + 1;
  }
  scrollRow = std::clamp(scrollRow, 0, std::max(0, shelfCount - visibleItems));

  // Prewarm the font cache with all visible folder names before drawing. Folder names are drawn
  // unconditionally on every render (unlike cover-fallback titles below), so without this, non-Latin
  // names (e.g. Japanese folders) hit FontDecompressor's slow single-slot fallback on every navigation
  // step -- one full ~64KB group decompression per name that lands in a different glyph group.
  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int i = scrollRow; i < std::min(scrollRow + visibleItems, shelfCount); i++) {
      prewarmBuf += shelves[i].folderName;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(UI_10_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::BOLD);
  }

  for (int i = scrollRow; i < std::min(scrollRow + visibleItems, shelfCount); i++) {
    const int itemY = contentTop + (i - scrollRow) * rowHeight;
    drawShelfRow(i, itemY, i == selectedItem);
  }

  if (shelfCount > visibleItems) {
    const int barX = pageWidth - metrics.scrollBarRightOffset - metrics.scrollBarWidth;
    const int thumbBarH = std::max(10, contentHeight * visibleItems / shelfCount);
    const int thumbBarY = contentTop + (contentHeight - thumbBarH) * scrollRow / (shelfCount - visibleItems);
    renderer.fillRect(barX, thumbBarY, metrics.scrollBarWidth, thumbBarH, true);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required.
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
}

void RecentBooksActivity::renderShelfBooksView(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (shelfBooks.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_FILES_FOUND));
    return;
  }

  const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
  const int cellWidth = gridWidth / GRID_COLS;
  const int cellHeight = getCellHeight(cellWidth);
  const int rowStride = cellHeight + GRID_ROW_GAP;
  const int visibleRows = getVisibleRows(cellHeight, contentHeight);
  const int bookCount = static_cast<int>(shelfBooks.size());
  const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;

  if (shelfContentIndex >= 0) {
    const int selectedRow = shelfContentIndex / GRID_COLS;
    if (selectedRow < shelfScrollRow) shelfScrollRow = selectedRow;
    if (selectedRow >= shelfScrollRow + visibleRows) shelfScrollRow = selectedRow - visibleRows + 1;
  }
  shelfScrollRow = std::clamp(shelfScrollRow, 0, std::max(0, totalRows - visibleRows));

  // See renderBooksTab: one peek row, no titles on it, badges filled synchronously.
  const int renderRows = std::min(totalRows - shelfScrollRow, visibleRows + 1);
  const int firstIdx = shelfScrollRow * GRID_COLS;
  const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
  const int titledLastIdx = std::min(firstIdx + visibleRows * GRID_COLS, bookCount) - 1;

  fillPageProgressNow(shelfBookProgress, nullptr, &shelfBooks, firstIdx, lastIdx);

  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int idx = firstIdx; idx <= titledLastIdx; idx++) {
      prewarmBuf += shelfBooks[idx].title;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(SMALL_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::REGULAR);
  }

  for (int idx = firstIdx; idx <= lastIdx; idx++) {
    const int local = idx - firstIdx;
    const int col = local % GRID_COLS;
    const int row = local / GRID_COLS;
    const int cellX = metrics.contentSidePadding + col * cellWidth;
    const int cellY = contentTop + row * rowStride;
    const int pct = idx < static_cast<int>(shelfBookProgress.size()) ? shelfBookProgress[idx].percent : -1;
    drawGridCell(cellX, cellY, cellWidth, cellHeight, shelfBooks[idx].coverBmpPath, shelfBooks[idx].title, pct,
                 idx == shelfContentIndex, /*drawTitle=*/idx <= titledLastIdx);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required.
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
  drawGridScrollBar(contentTop, contentHeight, totalRows, visibleRows, shelfScrollRow);
}

void RecentBooksActivity::drawGridScrollBar(const int contentTop, const int contentHeight, const int totalRows,
                                            const int visibleRows, const int topRow) {
  if (totalRows <= visibleRows) return;
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int barX = renderer.getScreenWidth() - metrics.scrollBarRightOffset - metrics.scrollBarWidth;
  const int thumbBarH = std::max(10, contentHeight * visibleRows / totalRows);
  const int thumbBarY = contentTop + (contentHeight - thumbBarH) * topRow / (totalRows - visibleRows);
  renderer.fillRect(barX, thumbBarY, metrics.scrollBarWidth, thumbBarH, true);
}

void RecentBooksActivity::buildTouchTargets(UiScreen& screen) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int pageWidth = renderer.getScreenWidth();
  const int pageHeight = renderer.getScreenHeight();
  const uint16_t bookMask = static_cast<uint16_t>(fui::InputTouch | fui::InputLongPress);

  if (openShelfIndex >= 0 && openShelfIndex < static_cast<int>(shelves.size())) {
    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    const int bookCount = static_cast<int>(shelfBooks.size());
    const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;
    const int renderRows = std::min(totalRows - shelfScrollRow, visibleRows + 1);
    const int firstIdx = shelfScrollRow * GRID_COLS;
    const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
    for (int idx = firstIdx; idx <= lastIdx; idx++) {
      const int local = idx - firstIdx;
      const int col = local % GRID_COLS;
      const int row = local / GRID_COLS;
      screen.frame().hit(fui::Rect{static_cast<int16_t>(metrics.contentSidePadding + col * cellWidth),
                                   static_cast<int16_t>(contentTop + row * rowStride), static_cast<int16_t>(cellWidth),
                                   static_cast<int16_t>(cellHeight)},
                         ACTION_SHELF_BOOK, static_cast<int16_t>(idx), bookMask);
    }
    return;
  }

  const int tabBarY = metrics.topPadding + metrics.headerHeight;
  const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
  const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
  if (selectedTab == 0) {
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    const int bookCount = static_cast<int>(recentBooks.size());
    const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;
    const int renderRows = std::min(totalRows - scrollRow, visibleRows + 1);
    const int firstIdx = scrollRow * GRID_COLS;
    const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
    for (int idx = firstIdx; idx <= lastIdx; idx++) {
      const int local = idx - firstIdx;
      const int col = local % GRID_COLS;
      const int row = local / GRID_COLS;
      screen.frame().hit(fui::Rect{static_cast<int16_t>(metrics.contentSidePadding + col * cellWidth),
                                   static_cast<int16_t>(contentTop + row * rowStride), static_cast<int16_t>(cellWidth),
                                   static_cast<int16_t>(cellHeight)},
                         ACTION_BOOK, static_cast<int16_t>(idx), bookMask);
    }
    return;
  }

  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int visibleItems = std::max(1, contentHeight / rowHeight);
  const int shelfCount = static_cast<int>(shelves.size());
  const int top = std::clamp(scrollRow, 0, std::max(0, shelfCount - visibleItems));
  for (int i = top; i < std::min(top + visibleItems, shelfCount); i++) {
    screen.frame().hit(fui::Rect{static_cast<int16_t>(metrics.contentSidePadding - 6),
                                 static_cast<int16_t>(contentTop + (i - top) * rowHeight - 4),
                                 static_cast<int16_t>(pageWidth - 2 * metrics.contentSidePadding + 12),
                                 static_cast<int16_t>(rowHeight + 8)},
                       ACTION_SHELF, static_cast<int16_t>(i), fui::InputTouch);
  }
}

bool RecentBooksActivity::routeLibraryTouch() {
  const auto route = routeTouch(mappedInput, /*withLongPress=*/true);
  if (route.routed) {
    lastInputMs = millis();
    coverWorkerCancelRequested_ = true;
    if (app.invalidated()) requestUpdate();
  }
  return static_cast<bool>(route);
}

bool RecentBooksActivity::tryPartialSelectionRedraw() {
  if (!lastRendered.valid) return false;
  if (openShelfIndex != lastRendered.openShelf || selectedTab != lastRendered.tab) return false;

  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();
  const auto pageHeight = renderer.getScreenHeight();
  auto* fcm = renderer.getFontCacheManager();

  if (openShelfIndex >= 0) {
    // Shelf-books grid: pure cell-to-cell move within the rendered scroll window.
    const int oldIdx = lastRendered.shelfContentIndex;
    const int newIdx = shelfContentIndex;
    if (contentIndex != lastRendered.contentIndex) return false;
    if (oldIdx == newIdx || oldIdx < 0 || newIdx < 0) return false;
    if (newIdx >= static_cast<int>(shelfBooks.size()) || oldIdx >= static_cast<int>(shelfBooks.size())) return false;

    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    // The move must not scroll (renderShelfBooksView would adjust shelfScrollRow).
    const int newRow = newIdx / GRID_COLS;
    if (newRow < shelfScrollRow || newRow >= shelfScrollRow + visibleRows) return false;
    if (shelfScrollRow != lastRendered.shelfScrollRow) return false;

    // The border ring never overlaps cell content, so the move is just erase + draw.
    for (const int idx : {oldIdx, newIdx}) {
      const int row = idx / GRID_COLS;
      const int col = idx % GRID_COLS;
      const int cellX = metrics.contentSidePadding + col * cellWidth;
      const int cellY = contentTop + (row - shelfScrollRow) * rowStride;
      drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, idx == newIdx);
    }
    return true;
  }

  // Main view: index 0 is the tab bar -- entering/leaving it changes the tab bar highlight, so
  // only moves between two real items qualify.
  const int oldIdx = lastRendered.contentIndex;
  const int newIdx = contentIndex;
  if (oldIdx == newIdx || oldIdx < 1 || newIdx < 1) return false;

  const int tabBarY = metrics.topPadding + metrics.headerHeight;
  const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
  const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  if (selectedTab == 0) {
    if (newIdx > static_cast<int>(recentBooks.size()) || oldIdx > static_cast<int>(recentBooks.size())) return false;
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    // The move must not scroll (renderBooksTab would adjust scrollRow).
    const int newRow = (newIdx - 1) / GRID_COLS;
    if (newRow < scrollRow || newRow >= scrollRow + visibleRows) return false;
    if (scrollRow != lastRendered.scrollRow) return false;

    // The border ring never overlaps cell content, so the move is just erase + draw.
    for (const int idx : {oldIdx - 1, newIdx - 1}) {
      const int row = idx / GRID_COLS;
      const int col = idx % GRID_COLS;
      const int cellX = metrics.contentSidePadding + col * cellWidth;
      const int cellY = contentTop + (row - scrollRow) * rowStride;
      drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, idx == newIdx - 1);
    }
    return true;
  }

  // Shelves list rows.
  if (newIdx > static_cast<int>(shelves.size()) || oldIdx > static_cast<int>(shelves.size())) return false;
  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int visibleItems = std::max(1, contentHeight / rowHeight);
  auto scrollOffsetFor = [visibleItems](const int selectedItem) {
    return selectedItem >= visibleItems ? selectedItem - visibleItems + 1 : 0;
  };
  if (scrollOffsetFor(newIdx - 1) != scrollOffsetFor(oldIdx - 1)) return false;
  const int scrollOffset = scrollOffsetFor(newIdx - 1);

  if (fcm) {
    renderer.prewarmText(UI_10_FONT_ID, (shelves[oldIdx - 1].folderName + ' ' + shelves[newIdx - 1].folderName).c_str(),
                         1 << EpdFontFamily::BOLD);
  }
  for (const int idx : {oldIdx - 1, newIdx - 1}) {
    const int itemY = contentTop + (idx - scrollOffset) * rowHeight;
    // Clear the full row footprint including the selection highlight's -6/-4 overhang.
    renderer.fillRect(metrics.contentSidePadding - 6, itemY - 4, pageWidth - 2 * metrics.contentSidePadding + 12,
                      rowHeight + 8, false);
    drawShelfRow(idx, itemY, idx == newIdx - 1);
  }
  if (fcm) fcm->clearCache();
  return true;
}

void RecentBooksActivity::render(RenderLock&&) {
  if (tryPartialSelectionRedraw()) {
    lastRendered.contentIndex = contentIndex;
    lastRendered.shelfContentIndex = shelfContentIndex;
    renderer.displayBuffer();
    return;
  }

  renderer.clearScreen();

  const auto pageWidth = renderer.getScreenWidth();
  const auto pageHeight = renderer.getScreenHeight();
  const auto& metrics = UITheme::getInstance().getMetrics();

  if (openShelfIndex >= 0 && openShelfIndex < static_cast<int>(shelves.size())) {
    GUI.drawHeader(renderer, Rect{0, metrics.topPadding, pageWidth, metrics.headerHeight},
                   shelves[openShelfIndex].folderName.c_str());

    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

    renderShelfBooksView(contentTop, contentHeight);

    const auto labels = mappedInput.mapLabels(tr(STR_BACK), tr(STR_SELECT), tr(STR_DIR_UP), tr(STR_DIR_DOWN));
    GUI.drawButtonHints(renderer, labels.btn1, labels.btn2, labels.btn3, labels.btn4);

    lastRendered = {true, openShelfIndex, selectedTab, contentIndex, scrollRow, shelfContentIndex, shelfScrollRow};
    renderUi();
    renderer.displayBuffer();
    return;
  }

  GUI.drawHeader(renderer, Rect{0, metrics.topPadding, pageWidth, metrics.headerHeight}, tr(STR_MENU_RECENT_BOOKS));

  std::vector<TabInfo> tabs;
  tabs.reserve(TAB_COUNT);
  tabs.push_back({tr(STR_TAB_BOOKS), selectedTab == 0});
  tabs.push_back({tr(STR_TAB_SHELVES), selectedTab == 1});
  const int tabBarY = metrics.topPadding + metrics.headerHeight;
  GUI.drawTabBar(renderer, Rect{0, tabBarY, pageWidth, metrics.tabBarHeight}, tabs, contentIndex == 0);

  const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
  const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  if (selectedTab == 0) {
    renderBooksTab(contentTop, contentHeight);
  } else {
    renderShelvesTab(contentTop, contentHeight);
  }

  const auto labels = mappedInput.mapLabels(tr(STR_HOME), tr(STR_SELECT), tr(STR_DIR_UP), tr(STR_DIR_DOWN));
  GUI.drawButtonHints(renderer, labels.btn1, labels.btn2, labels.btn3, labels.btn4);

  lastRendered = {true, openShelfIndex, selectedTab, contentIndex, scrollRow, shelfContentIndex, shelfScrollRow};
  renderUi();
  renderer.displayBuffer();
}
